name: Release

on:
  push:
    tags:
    - 'v*'
    - 'test-v*'
  pull_request:

env:
  ALPINE_VERSION: 3.22.0
  DOCKER_BUILDKIT: 1

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
        persist-credentials: false

    - name: Install the arm64 emulator for binfmt_misc
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install arm64

    - name: Build the mkimage images
      run: |
        make mkimage ARCH=x86_64
        make mkimage ARCH=aarch64

    - name: Build the std edition
      run: |
        make iso EDITION=std ARCH=x86_64
        make iso EDITION=std ARCH=aarch64

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          iso/alpine-lima-std-*
